### ISSUE TITLE
I have some question

### ISSUE THREAD

**Issue by MasterWall** [LeiBAI/DCRNN_Pytorch#2]
Q1：args.add_argument('--lr_milestones', default='20,30,40,50', type=str)，the epochs is 100，maybe lr_milestones should be set '20,30,40,50,60,70,80,100'？
Q2：args.add_argument('--diffusion_step', default=2, type=int)，which is the diffusion convolutional step? the paper is 3，why here is 2？
Q3：In the DCRNNModel.py，class DCRNN，the num_layers=1, which is the number of diffusion convolutional layers in the Encoder and Decoder? the paper is 3，why here is 1？
Q4：I run your code and fail to use GPU, but success to use CPU, so I want to use GPU to run your code, what should I change the code?

**Comment by MasterWall** [comment]
well，for the Q4，I change a little code in the DiffusionGCN.py，in class DiffusionGCN2(nn.Module):，
x1 = torch.einsum('ij, bjk -> bik', support.cuda(), x0.cuda())
x2 = 2 * torch.einsum('ij, bjk -> bik', support.cuda(), x1.cuda()) - x0.cuda()
the support, x0 and x1 add".cuda()"，which can success to run with GPU

**Comment by LeiBAI** [comment]
@ChenAugustus  For Q1: the minimum lr is 1e-6 in the original paper. For Q2 and Q3, they are parameters for the model, so of course, you can set diffusion_step = 3 and num_layers=3
